version: "3.3"

services:
  vstup-twitter-bot:
    container_name: vstup-twitter-bot
    build:
      dockerfile: Dockerfile
      context: .
    restart: always
    volumes:
      - ./storage.db:/app/storage.db
    environment:
      - CHAT_ID
      - TELEGRAM_TOKEN
      - TWITTER_PASSWORD
      - TWITTER_USERNAME
      - TWITTER_COOKIES
      - PYTHONUNBUFFERED=1
